### ISSUE TITLE
Fullscreen mode and/or Controller support?

### ISSUE THREAD

**Issue by alfredolvera** [mattruzzi/Nativefier-YouTube-on-TV-for-Desktop#1]
Hi. Thanks for the great app, it's incredible that Google doesn't do this.

A couple of questions: Is it possible to run it in fullscreen mode? With no windows borders. 

Do you have any plans for controller navigation support?

I'm running Windows 10, 64.

Cheers!

**Comment by matthewruzzi** [comment]
I don't have a windows computer to test it on, but you could try the following:
https://we.tl/t-uSZdkNmkbb
I'm not sure how windows handles fullscreen for electron apps.

**Comment by matthewruzzi** [comment]
You can use it with a controller if you have a way of mapping the buttons on the controller to keys on the keyboard. (eg. up button on controller = up button on keyboard)
