### ISSUE TITLE
Latest build max resolution issue

### ISSUE THREAD

**Issue by ghost** [mattruzzi/Nativefier-YouTube-on-TV-for-Desktop#4]
Hi--love the app--However,  On my 1080p screen on Linux Laptop and Windows Desktop, the app only offers 720p max.  On my 720p TV, it only shows 480p max.  Seems like it registers one step below the screen size.

Thanks.

**Comment by ghost** [comment]
Update..played around with another build in another project..seems the app has to start in full screen to register the higher resolution of the display.

**Comment by cannedpeanut** [comment]
What was your solution? I'm not sure how to launch this in full screen on Windows.
